#nome da ppipe
name: 'execucao deploy'
#trigger gatilho de execucao
on :
  workflow_run:
    workflows: [ 'execucao manual']
    types: 
      - completed

jobs:
#descricao job
  e2e-tests:
  #descricao maquin
    runs-on: ['ubuntu-latest']
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    #passp a passo
    steps:  
    - uses: actions/checkout@v4

    - name: Instalando yarn
      run: npm i -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Install Cypress
      run: yarn add --dev cypress

    - name: Run Cypress tests
      run: npx cypress run

    - name: Run Cypress tests
      run: npx cypress run

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: relatorio de testes
        path: ./playwright-report  





