
name: 'Execução Deploy - Testes Web Cypress'

on :
  workflow_run:
    workflows: [ 'execucao Deploy']
    types: 
      - completed

jobs:

  e2e-tests:
  
    runs-on: ['ubuntu-latest']
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
  
    steps:  
    - uses: actions/checkout@v4

    - name: Instalando yarn
      run: npm i -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Install Cypress
      run: yarn add --dev cypress

    - name: Run Cypress tests
      run: |
        npx cypress run --reporter junit --reporter-options "mochaFile=./test-report/results-[hash].xml"
      env:
        CYPRESS_INSTALL_BINARY: 0

    - name: Upload do relatório de testes
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: relatorio-de-testes
        path: ./test-report