
name: 'Execução Agendada - Testes Web Cypress'

on:
  schedule:
    - cron: "30 19 * * *"

jobs:

  e2e-tests:

    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v4

    - name: Instalando yarn
      run: npm i -g yarn

    - name: Install dependencies
      run: yarn install

    - name: Install Cypress
      run: yarn add --dev cypress

    - name: Run Cypress tests
      run: npx cypress run

      env:
        CYPRESS_INSTALL_BINARY: 0

    - name: Upload do relatório de testes
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: relatorio-de-testes
        path: ./test-report





